import Route from '@ioc:Adonis/Core/Route'

Route.post('api/v1/auth/login', 'AuthController.login').middleware('throttle:global')
Route.post('api/v1/auth/logout', 'AuthController.logout')
  .middleware('auth')
  .middleware('throttle:global')
Route.get('api/v1/profile', 'AuthController.getProfile')
  .middleware('auth')
  .middleware('throttle:global')

Route.post('api/v1/users', 'UsersController.store').middleware('throttle:global')
Route.get('api/v1/users/:id', 'UsersController.index')
  .middleware('auth')
  .middleware('throttle:global')
Route.patch('api/v1/users/update/:id', 'UsersController.update')
  .middleware('auth')
  .middleware('throttle:global')
Route.delete('api/v1/users/:id', 'UsersController.destroy')
  .middleware('auth')
  .middleware('throttle:global')

Route.post('api/v1/tasks', 'TasksController.store').middleware('auth').middleware('throttle:global')
Route.get('api/v1/tasks/:id', 'TasksController.index')
  .middleware('auth')
  .middleware('throttle:global')
Route.patch('api/v1/tasks/update/:id', 'TasksController.update')
  .middleware('auth')
  .middleware('throttle:global')
Route.delete('api/v1/tasks/:id', 'TasksController.destroy')
  .middleware('auth')
  .middleware('throttle:global')
